# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr", ".direnv", ".eggs", ".git", ".git-rewrite", ".hg", ".ipynb_checkpoints",
    ".mypy_cache", ".nox", ".pants.d", ".pyenv", ".pytest_cache", ".pytype",
    ".ruff_cache", ".svn", ".tox", ".venv", ".vscode", "__pypackages__", "_build",
    "buck-out", "build", "dist", "node_modules", "site-packages", "venv",
]
line-length    = 90
indent-width   = 4
target-version = "py313"


[lint]
extend-select      = ["I", "N"]
ignore             = ["E501", "F401", "N806"] # long lines, unused imports, uppercase vars
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
fixable            = ["ALL"]
unfixable          = []

[lint.per-file-ignores]
"__init__.py"             = ["E402", "F403", "I"]
"**/{tests,docs,tools}/*" = ["E402", "F403", "N", "I"]


[format]
quote-style                = "double"
indent-style               = "space"
skip-magic-trailing-comma  = false
line-ending                = "auto"
docstring-code-format      = true
docstring-code-line-length = "dynamic"
